### ISSUE TITLE
设置代理

### ISSUE THREAD

**Issue by Jungchen** [page-pipepline/pipeline-node-server#1]
模板中使用网络请求的地址,
在服务端启动后变成了 http://localhost:7011 开头的了(404 请求的接口不存在 ) ,
怎么设置代理为正确的地址.

**Comment by CntChen** [comment]
模板中使用的地址，是不是使用了相对路径。
在编辑器中, 预览到的页面是由服务端托管的，所以相对路径会转化为服务端(http://localhost:7011 ）下的网址。
模板中要写全；或者在浏览器中用代理，转到真正需要的后端。
